env:
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - standard
  - plugin:prettier/recommended
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - no-floating-promise
rules:
  # no-console: 1
  no-underscore-dangle: 0
  no-use-before-define: 0
  semi: 0
  radix: 0
  no-floating-promise/no-floating-promise: 2
